# Generated by Django 5.0.7 on 2024-09-05 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_remove_category_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydata',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_data', to='features.category'),
        ),
    ]
