# Generated by Django 5.0.7 on 2024-09-06 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_alter_categorydata_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tansaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('category_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.categorydata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.user')),
            ],
        ),
    ]
