# Generated by Django 5.0.7 on 2024-09-06 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0007_remove_tansaction_time_tansaction_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(auto_now=True)),
                ('category_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.categorydata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.user')),
            ],
        ),
    ]
