# Generated by Django 5.0.7 on 2024-09-06 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0010_numberplate_alter_parking_number_plate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='number_plate',
        ),
    ]
