# Generated by Django 5.0.7 on 2024-09-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0011_remove_user_number_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydata',
            name='image',
            field=models.URLField(),
        ),
    ]
