# Generated by Django 5.0.7 on 2024-09-07 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0012_alter_categorydata_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tansaction',
            name='category_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoryData', to='features.categorydata'),
        ),
    ]
