# Generated by Django 5.0.7 on 2024-09-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0013_alter_tansaction_category_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='tansaction',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
